//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWIcon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWIcon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application cannot be updated. It is likely not a ClickOnce application..
        /// </summary>
        internal static string msgUpdateInvalidApplicationDeployment {
            get {
                return ResourceManager.GetString("msgUpdateInvalidApplicationDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update feature is turned off in this version..
        /// </summary>
        internal static string msgUpdateLocalDeployment {
            get {
                return ResourceManager.GetString("msgUpdateLocalDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available. You are using the latest version of the application..
        /// </summary>
        internal static string msgUpdateNoUpdate {
            get {
                return ResourceManager.GetString("msgUpdateNoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check for a new version of the application. The ClickOnce deployment is corrupt. Please redeploy the application and try again..
        /// </summary>
        internal static string msgUpdatePackageCorrupt {
            get {
                return ResourceManager.GetString("msgUpdatePackageCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version of the application cannot be downloaded at this time. \n\nPlease check your network connection, or try again later..
        /// </summary>
        internal static string msgUpdateServerInaccessable {
            get {
                return ResourceManager.GetString("msgUpdateServerInaccessable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for updates on the server..
        /// </summary>
        internal static string msgUpdateStated {
            get {
                return ResourceManager.GetString("msgUpdateStated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been upgraded, and will now restart..
        /// </summary>
        internal static string msgUpdateSuccessRestart {
            get {
                return ResourceManager.GetString("msgUpdateSuccessRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been long time since the last time you moved. It is time to be active..
        /// </summary>
        internal static string strActivityReminderNote {
            get {
                return ResourceManager.GetString("strActivityReminderNote", resourceCulture);
            }
        }
    }
}
